---
# tasks file for kops-install
#

- name: Kops | Get binary
  get_url:
    url: "{{ kops_download_path }}"
    dest: /usr/bin/kops
    owner: root
    group: root
    mode: 0755
    force: yes
  become: true  

- name: Kubectl | Get binary
  get_url:
    url: "{{ kubectl_download_path }}"
    dest: /usr/bin/kubectl
    owner: root
    group: root
    mode: 0755
    force: yes
  become: true
